name: slaq build

on:
  release:
    types: [ published ]
  push:
    branches:
      - v4
  pull_request:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        os: [ 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    name: build
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run build script
        run: bash ./scripts/build.sh "$(pwd)/dependencies"
        shell: bash
      - name: Upload Coverage To Codecov
        uses: codecov/codecov-action@v3
